#!/usr/bin/env bash
# Cloud Agent start phase: per-boot runtime initialization.
# Starts the local PostgreSQL daemon, ensures the app database and
# connection env exist, and applies Prisma migrations. Idempotent and
# safe to run on every boot. The Next.js dev server runs as a terminal.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
PGDATA="${PGDATA:-$HOME/.profuel/pgdata}"
PGPORT="${PGPORT:-5432}"
DB_NAME="${DB_NAME:-profuel}"
LOCAL_DB_URL="postgresql://ubuntu@127.0.0.1:${PGPORT}/${DB_NAME}?schema=public"

PGBIN="$(dirname "$(ls -d /usr/lib/postgresql/*/bin/postgres | sort -V | tail -1)")"

echo "==> Starting PostgreSQL (if not already running)"
if ! "$PGBIN/pg_isready" -h 127.0.0.1 -p "$PGPORT" >/dev/null 2>&1; then
  # Clean up any stale postmaster lock from a previous boot.
  rm -f "$PGDATA/postmaster.pid" 2>/dev/null || true
  "$PGBIN/pg_ctl" -D "$PGDATA" -o "-p ${PGPORT} -k /tmp" -l "$HOME/.profuel/pg.log" -w start
fi

echo "==> Waiting for PostgreSQL to accept connections"
for _ in $(seq 1 30); do
  if "$PGBIN/pg_isready" -h 127.0.0.1 -p "$PGPORT" >/dev/null 2>&1; then break; fi
  sleep 1
done
"$PGBIN/pg_isready" -h 127.0.0.1 -p "$PGPORT"

echo "==> Ensuring database '${DB_NAME}' exists"
if ! "$PGBIN/psql" -h 127.0.0.1 -p "$PGPORT" -U ubuntu -d postgres -tAc \
  "SELECT 1 FROM pg_database WHERE datname='${DB_NAME}'" | grep -q 1; then
  "$PGBIN/createdb" -h 127.0.0.1 -p "$PGPORT" -U ubuntu "${DB_NAME}"
fi

echo "==> Writing local .env for Prisma and Next.js"
cd "$REPO_DIR"
if [ ! -f .env ] || ! grep -q "127.0.0.1:${PGPORT}/${DB_NAME}" .env 2>/dev/null; then
  cat > .env <<EOF
# Local development database (auto-generated by .cursor/scripts/start.sh).
# Production uses Neon; see .env.example.
DATABASE_URL="${LOCAL_DB_URL}"
DATABASE_URL_UNPOOLED="${LOCAL_DB_URL}"
EOF
fi

echo "==> Applying Prisma migrations"
export DATABASE_URL="${LOCAL_DB_URL}"
export DATABASE_URL_UNPOOLED="${LOCAL_DB_URL}"
npx prisma migrate deploy

echo "==> Start phase complete (Postgres up, schema migrated)"
